"""init_db

Revision ID: 1eb116fac4d3
Revises: 
Create Date: 2022-06-23 13:36:57.767404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1eb116fac4d3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mutations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('rsid', sa.String(length=16), nullable=False),
    sa.Column('link', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_mutations_rsid'), 'mutations', ['rsid'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('telegram_user_id', sa.Integer(), nullable=False),
    sa.Column('telegram_chat_id', sa.Integer(), nullable=False),
    sa.Column('registered_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_uploaded', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_users_telegram_user_id'), 'users', ['telegram_user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_telegram_user_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_mutations_rsid'), table_name='mutations')
    op.drop_table('mutations')
    # ### end Alembic commands ###
